# Generated by Django 5.0.7 on 2024-10-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaign", "0005_delete_qaparameters"),
    ]

    operations = [
        migrations.CreateModel(
            name="QAParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qa_parameters", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("organisation_name", models.CharField(max_length=255)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "qa_parameters",
            },
        ),
    ]
