# Generated by Django 5.0.7 on 2024-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_parameters", "0002_remove_qaparameters_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="qaparameters",
            name="parameters_name",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
