# Generated by Django 5.0.7 on 2024-09-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0002_campaign_contact_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(default="not_started", max_length=255),
        ),
    ]
