# Generated by Django 4.1.13 on 2024-09-30 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0003_campaign_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_logs", models.CharField(max_length=255)),
                ("transcript", models.TextField()),
                ("organisation_name", models.CharField(max_length=255, null=True)),
                ("summary", models.TextField()),
                ("qa_analysis", models.JSONField(default=[])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "transcript",
            },
        ),
        migrations.CreateModel(
            name="QAParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qa_parameters", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "qa_parameters",
            },
        ),
    ]
