# Generated by Django 5.0.7 on 2024-10-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0004_transcript_qaparameters"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QAParameters",
        ),
    ]
