# Generated by Django 4.1.13 on 2024-10-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0005_delete_qaparameters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="contact_list",
        ),
        migrations.AddField(
            model_name="campaign",
            name="summarization_promt",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="ContactList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_name", models.CharField(max_length=255)),
                ("contact_list", models.JSONField(default=[])),
                ("is_active", models.BooleanField(default=False)),
                ("organisation_name", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_lists",
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "contact_list",
            },
        ),
    ]
