# Generated by Django 4.1.13 on 2024-10-03 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0006_remove_campaign_contact_list_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="summarization_promt",
            new_name="summarization_prompt",
        ),
    ]
