# Generated by Django 4.1.13 on 2024-10-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0009_campaign_qa_parameters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_note", models.TextField()),
                ("schedule_date", models.DateTimeField()),
                ("is_ongoing", models.BooleanField(default=False)),
                ("is_finished", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(default="SYSTEM", max_length=255)),
                ("modified_by", models.CharField(default="SYSTEM", max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_campaign",
                        to="campaign.campaign",
                    ),
                ),
            ],
        ),
    ]
