# Generated by Django 5.0.7 on 2024-09-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="is_delete",
            field=models.CharField(default=False,max_length=255),
        ),
        migrations.AlterField(
            model_name="provider",
            name="provider_config",
            field=models.JSONField(),
        ),
    ]
