# Generated by Django 5.0.7 on 2024-09-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_provider_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
