# Generated by Django 4.1.13 on 2024-10-07 20:18

from django.db import migrations


def insert_providers(apps, schema_editor):
    Provider = apps.get_model("provider", "Provider")
    providers = [
        {
            "provider_name": "OpenAI",
            "provider_config": {
                "api_key": "your-openai-api-key",
                "base_url": "https://api.openai.com",
                "model_name":"gpt-4o"
            },
            "provider_type": "llm",
            "is_delete": False,
        },
        {
            "provider_name": "ElevenLabs",
            "provider_config": {
                "api_key": "0",
                "model_id": "eleven_turbo_v2",
                "voice_id": "S3TQJCIBrHC9g8aQbb76",
                "stability": 0.1,
                "voice_name": "Jessica-1",
                "voice_type": "eleven_labs",
                "similarity_boost": 0.95,
                "optimize_streaming_latency": 4,
                "experimental_input_streaming": "0",
            },
            "provider_type": "voice",
            "is_delete": False,
        },       
        {
            "provider_name": "Twilio",
            "provider_config": {
                "from_number": "+19016213151",
               
            },
            "provider_type": "telephony",
            "is_delete": False,
        },
        {
            "provider_name": "Telnyx",
            "provider_config": {
                "from_number": "+18663310884",
               
            },
            "provider_type": "telephony",
            "is_delete": False,
        },        
    ]
    Provider.objects.bulk_create([Provider(**provider) for provider in providers])


class Migration(migrations.Migration):
    dependencies = [
        ("provider", "0004_alter_provider_is_delete"),
    ]

    operations = [
        migrations.RunPython(insert_providers),
    ]