# Generated by Django 5.1.2 on 2024-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonoapp', '0003_remove_role_organisation_name_alter_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=0)),
                ('organisation_name', models.CharField(max_length=255, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='SYSTEM', max_length=255, null=True)),
                ('modified_by', models.CharField(default='SYSTEM', max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
        ),
    ]
