# Generated by Django 5.0.7 on 2024-10-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zonoapp", "0004_credits"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organisation_name", models.CharField(max_length=255, unique=True)),
                ("rate", models.IntegerField(default=10)),
            ],
        ),
    ]
