# Generated by Django 5.0.7 on 2024-10-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zonoapp", "0005_creditrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organisation_name", models.CharField(max_length=255, unique=True)),
                ("user_id", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
                ("payment_response", models.CharField(max_length=255)),
            ],
        ),
    ]
