# Generated by Django 5.0.7 on 2024-10-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zonoapp", "0006_paymentstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentstatus",
            name="amount",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
