# Generated by Django 5.0.7 on 2024-10-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zonoapp", "0007_paymentstatus_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentstatus",
            name="organisation_name",
            field=models.CharField(max_length=255),
        ),
    ]
