# Generated by Django 5.0.7 on 2024-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zonoapp", "0009_insert_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organisation_name", models.CharField(max_length=255, unique=True)),
                ("balance", models.FloatField(default=0)),
            ],
        ),
    ]
