# Generated by Django 5.0.7 on 2024-10-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zonoapp", "0011_credits_balance_credits_call_rate_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AvailableBalance",
        ),
        migrations.DeleteModel(
            name="CreditRate",
        ),
    ]
