# Generated by Django 5.1.2 on 2024-11-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('provider', '0005_insert_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_telephony',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telephony', to='provider.provider'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm', to='provider.provider'),
        ),
    ]
