# Generated by Django 5.0.7 on 2024-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voice_id", models.CharField(max_length=255)),
                ("voice_provider", models.CharField(max_length=255)),
                ("oragnisation_name", models.CharField(max_length=255)),
                ("voice_configuration", models.CharField(max_length=255)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "voice",
            },
        ),
    ]
