# Generated by Django 5.0.7 on 2024-09-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0002_alter_voice_voice_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="voice",
            name="created_by",
            field=models.CharField(default="SYSTEM", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="voice",
            name="modified_by",
            field=models.CharField(default="SYSTEM", max_length=255, null=True),
        ),
    ]
