# Generated by Django 5.0.7 on 2024-09-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0003_voice_created_by_voice_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="voice",
            name="voice_name",
            field=models.CharField(default="der", max_length=255),
            preserve_default=False,
        ),
    ]
