# Generated by Django 5.0.7 on 2024-09-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_voice_created_by_voice_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='voice_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
